name: Release

on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: silver886/github-actions/checkout@master
      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Repository to lowercase
        id: lower-repo
        run: echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.ref_name }}
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.ref_type == 'tag' && 'latest' || github.sha }}
